name: sleep_care
description: 수면, 코골이, 통계를 관리하는 헬스케어 앱
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  intl: ^0.19.0
  health: ^13.3.1
  noise_meter: ^5.1.0
  permission_handler: ^12.0.3
  kakao_flutter_sdk_user: ^1.9.7
  http: ^1.6.0
  record: ^7.1.1
  path_provider: ^2.1.6
  audioplayers: ^6.8.1
  web_socket_channel: ^3.0.1
  flutter_local_notifications: ^18.0.1
  vibration: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png
    - assets/sleep.png

flutter_native_splash:
  image: assets/splash_logo.png
  fullscreen: true
  android: true
  ios: true

  android_12:
    image: assets/splash_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"
